// Read-only public fallback used only when the persistent database is unavailable.
// It never accepts writes and is never used by Admin/order routes.
const products = [
  {
    "id": "pin-01",
    "sku": "MED-014",
    "name": "Pin Estetoscopio Rosa con Corazón",
    "category": "Medicina",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": 10000,
    "stock": 18,
    "image": "/images/pins/estetoscopio-pin.webp",
    "description": "Estetoscopio médico en relieve 3D color rosa con dije de corazón rojo. Ideal para enfermeros, médicos y estudiantes de medicina.",
    "badge": "Top Medicina 🩺",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": 10000,
    "galleryImages": []
  },
  {
    "id": "pin-02",
    "sku": "SIM-001",
    "name": "Pin Corazón Rojo Clásico",
    "category": "Ofertas",
    "target_type": "crocs",
    "price": 10000,
    "promo_price": 8000,
    "stock": 11,
    "image": "/images/pins/corazon-rojo-pin.webp",
    "description": "Corazón rojo inflado en alto relieve de goma PVC suave. El detalle romántico y tierno perfecto para combinar.",
    "badge": "En Oferta ❤️",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": 8000,
    "galleryImages": []
  },
  {
    "id": "pin-03",
    "sku": "PER-008",
    "name": "Pin Gatita Bow (Estilo Hello Kitty)",
    "category": "Personajes",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": null,
    "stock": 14,
    "image": "/images/pins/gatita-bow-pin.webp",
    "description": "Carita tierna de gatita blanca con su icónico lazo rosa. De los pins más pedidos por grandes y chicos.",
    "badge": "Más Vendido ✨",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-04",
    "sku": "ANI-003",
    "name": "Pin Capibara con Florcita",
    "category": "Animales",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": null,
    "stock": 8,
    "image": "/images/pins/capivara-pin.webp",
    "description": "El animal más querido de internet con florcita rosa en la cabeza. Relieve 3D de alta definición.",
    "badge": "Favorito 🦦",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-05",
    "sku": "COM-002",
    "name": "Pin Aguacate Cool con Lentes",
    "category": "Comida",
    "target_type": "crocs",
    "price": 10000,
    "promo_price": null,
    "stock": 15,
    "image": "/images/pins/avocado-pin.webp",
    "description": "Palta / aguacate maduro y simpático usando lentes de sol oscuros. Estilo y frescura en tu calzado.",
    "badge": "Tendencia 🥑",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-06",
    "sku": "FLO-005",
    "name": "Pin Florcita Daisy Sonriente",
    "category": "Flores",
    "target_type": "crocs",
    "price": 10000,
    "promo_price": null,
    "stock": 20,
    "image": "/images/pins/flower-pin.webp",
    "description": "Margarita blanca y amarilla con carita alegre estilo Murakami. Llena de vida y buena vibra.",
    "badge": "Clásico 🌼",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-07",
    "sku": "DEP-001",
    "name": "Pin Balón de Fútbol Estrella",
    "category": "Deportes",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": null,
    "stock": 7,
    "image": "/images/pins/futbol-pin.webp",
    "description": "Pelota de fútbol clásica con estrellas doradas. Indispensable para los fanáticos del deporte rey.",
    "badge": "Fútbol ⚽",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-08",
    "sku": "GAM-003",
    "name": "Pin Control Gamer Joystick Arcade",
    "category": "Personajes",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": null,
    "stock": 6,
    "image": "/images/pins/gamer-pin.webp",
    "description": "Mando retro de videojuegos con cruceta y botones de colores. El preferido de los streamers y gamers.",
    "badge": "Gamer 🎮",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-09",
    "sku": "COM-007",
    "name": "Pin Rebanada de Pizza Pepperoni",
    "category": "Comida",
    "target_type": "crocs",
    "price": 10000,
    "promo_price": null,
    "stock": 9,
    "image": "/images/pins/pizza-pin.webp",
    "description": "Porción de pizza con queso derretido y rodajas de pepperoni. Un clásico para personalizar con humor.",
    "badge": "Delicioso 🍕",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-10",
    "sku": "COM-010",
    "name": "Pin Vaso Boba Tea Kawaii",
    "category": "Comida",
    "target_type": "crocs",
    "price": 10000,
    "promo_price": null,
    "stock": 8,
    "image": "/images/pins/boba-pin.webp",
    "description": "Vaso de té de perlas con pajita y carita tierna. Súper popular entre los amantes del bubble tea.",
    "badge": "Kawaii 🧋",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-11",
    "sku": "MET-004",
    "name": "Pin Corazón Glitter Dorado Lux",
    "category": "Ofertas",
    "target_type": "crocs",
    "price": 15000,
    "promo_price": 12000,
    "stock": 2,
    "image": "/images/pins/heart-glitter-pin.webp",
    "description": "Acabado brillante con microglitter holográfico dorado y resina espejada. Toque de elegancia y brillo.",
    "badge": "¡Últimas 2! ⚡",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": 12000,
    "galleryImages": []
  },
  {
    "id": "pin-12",
    "sku": "ANI-006",
    "name": "Pin Baby Dino T-Rex Verde",
    "category": "Animales",
    "target_type": "crocs",
    "price": 12000,
    "promo_price": null,
    "stock": 0,
    "image": "/images/pins/dino-pin.webp",
    "description": "Dinosaurio verde simpático en goma suave. Reposición de stock en camino.",
    "badge": "Agotado",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-13",
    "sku": "PCK-MED01",
    "name": "Pack Medicina 5 Pins (Promo Especial)",
    "category": "Packs",
    "target_type": "crocs",
    "price": 45000,
    "promo_price": 45000,
    "stock": 5,
    "image": "/images/pins/estetoscopio-pin.webp",
    "description": "Kit completo para personal de salud: Estetoscopio, Corazón, Curita, Cápsula y Dije Médico. Llevá 5 por solo Gs. 45.000.",
    "badge": "Pack 5x 🩺",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": 45000,
    "galleryImages": []
  },
  {
    "id": "pin-14",
    "sku": "PCK-LET02",
    "name": "Pack Letras & Good Vibes (Armá tu Nombre)",
    "category": "Letras",
    "target_type": "crocs",
    "price": 40000,
    "promo_price": null,
    "stock": 6,
    "image": "/images/pins/crocs-jibbitz-charms-pins-1.webp",
    "description": "Combiná iniciales, letras en relieve y dijes positivos para personalizar tu Crocs con tu nombre.",
    "badge": "Armá tu Nombre 🔤",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-15",
    "sku": "PCK-DIS03",
    "name": "Pack Disney Clásicos 5 Charms",
    "category": "Packs",
    "target_type": "crocs",
    "price": 50000,
    "promo_price": null,
    "stock": 4,
    "image": "/images/pins/crocs-jibbitz-charm-stitch-mickey-avenge-2.webp",
    "description": "Pack con 5 pins de personajes favoritos estilo animación clásica.",
    "badge": "Pack 5 Charms 🎁",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "crocs",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-steth-01",
    "sku": "EST-EKG01",
    "name": "Dije Clip Estetoscopio Corazón EKG Rosa",
    "category": "Cardiología",
    "target_type": "estetoscopio",
    "price": 18000,
    "promo_price": 15000,
    "stock": 15,
    "image": "/images/pins/steth-charm-ekg.webp",
    "description": "Dije clip metálico en oro rosa con esmalte de corazón y pulso EKG. Se abraza con seguridad al tubo de cualquier estetoscopio estándar (Littmann, MDF, etc.) sin rayarlo.",
    "badge": "Top Esteto 🩺",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": 15000,
    "galleryImages": []
  },
  {
    "id": "pin-steth-02",
    "sku": "EST-DEN02",
    "name": "Charm Estetoscopio Diente Molar Kawaii (Odonto)",
    "category": "Odontología",
    "target_type": "estetoscopio",
    "price": 18000,
    "promo_price": null,
    "stock": 12,
    "image": "/images/pins/steth-charm-tooth.webp",
    "description": "Diente molar sonriente con cofia rosa en resina esmaltada de alta definición. El accesorio clínico ideal para odontólogos, cirujanos dentales y estudiantes.",
    "badge": "Odontología 🦷",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-steth-03",
    "sku": "EST-VET03",
    "name": "Dije Estetoscopio Patita Pet (Veterinaria)",
    "category": "Veterinaria",
    "target_type": "estetoscopio",
    "price": 18000,
    "promo_price": null,
    "stock": 14,
    "image": "/images/pins/steth-charm-paw.webp",
    "description": "Huella de mascota en oro rosa y verde menta pastel. Broche posterior que no resbala en la goma del tubo. El preferido de veterinarios.",
    "badge": "Veterinaria 🐾",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-steth-04",
    "sku": "EST-DUO04",
    "name": "Pack Combo Clínico: Dije Estetoscopio + Pin Crocs a Juego",
    "category": "Packs Médicos",
    "target_type": "estetoscopio",
    "price": 28000,
    "promo_price": 25000,
    "stock": 8,
    "image": "/images/pins/steth-charm-duo.webp",
    "description": "¡El combo definitivo! Incluye 1 clip para tubo de estetoscopio + 1 pin para tus calzados Crocs con diseño clínico a juego. Llevá ambos y combiná tu guardia médica.",
    "badge": "Combo 2 en 1 🎁",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": 25000,
    "galleryImages": []
  },
  {
    "id": "pin-steth-05",
    "sku": "EST-COR05",
    "name": "Charm Estetoscopio Corazón Glitter Lux",
    "category": "Cardiología",
    "target_type": "estetoscopio",
    "price": 18000,
    "promo_price": null,
    "stock": 10,
    "image": "/images/pins/heart-glitter-pin.webp",
    "description": "Corazón brillante con microglitter holográfico dorado y montura especial para tubuladura de estetoscopio.",
    "badge": "Glitter Lux ✨",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": null,
    "galleryImages": []
  },
  {
    "id": "pin-steth-06",
    "sku": "EST-MIN06",
    "name": "Pin Mini Estetoscopio Clínico 3D Rosa",
    "category": "Cardiología",
    "target_type": "estetoscopio",
    "price": 18000,
    "promo_price": 15000,
    "stock": 16,
    "image": "/images/pins/estetoscopio-pin.webp",
    "description": "Dije en relieve 3D de alta definición que se abraza al estetoscopio para personalizar tu herramienta de trabajo diaria.",
    "badge": "Top Ventas 🩺",
    "active": true,
    "featured": false,
    "gallery_images": "[]",
    "targetType": "estetoscopio",
    "promoPrice": 15000,
    "galleryImages": []
  }
];
const categories = [
  {
    "id": "fallback-cat-1",
    "name": "Personajes",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-2",
    "name": "Medicina",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-3",
    "name": "Animales",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-4",
    "name": "Flores",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-5",
    "name": "Letras",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-6",
    "name": "Deportes",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-7",
    "name": "Comida",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-8",
    "name": "Viajes",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-9",
    "name": "Packs",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-10",
    "name": "Ofertas",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-11",
    "name": "Especiales",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-12",
    "name": "Otros",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-18",
    "name": "Pins Metálicos",
    "target_type": "crocs",
    "targetType": "crocs",
    "active": true
  },
  {
    "id": "fallback-cat-13",
    "name": "Cardiología",
    "target_type": "estetoscopio",
    "targetType": "estetoscopio",
    "active": true
  },
  {
    "id": "fallback-cat-14",
    "name": "Odontología",
    "target_type": "estetoscopio",
    "targetType": "estetoscopio",
    "active": true
  },
  {
    "id": "fallback-cat-15",
    "name": "Veterinaria",
    "target_type": "estetoscopio",
    "targetType": "estetoscopio",
    "active": true
  },
  {
    "id": "fallback-cat-16",
    "name": "Packs Médicos",
    "target_type": "estetoscopio",
    "targetType": "estetoscopio",
    "active": true
  },
  {
    "id": "fallback-cat-17",
    "name": "Ofertas",
    "target_type": "estetoscopio",
    "targetType": "estetoscopio",
    "active": true
  }
];
const settings = {
  "storeName": "PINPOP",
  "tagline": "Pins para tus Crocs • Dale onda a tus calzados ✨",
  "whatsappNumber": "595991950031",
  "deliveryFee": 15000,
  "freeDeliveryThreshold": 100000,
  "promoBanner": "¡Dale personalidad a tus Crocs! ✨ Elegí tus pins favoritos. Envíos a todo Paraguay 🛵"
};

module.exports = {
  products,
  categories,
  settings,
  getProductById(id) { return products.find(p => p.id === id) || null; },
  getSeoProducts() { return products.map(p => ({ id: p.id, name: p.name, updatedAt: null })); }
};
