const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
const checks=[];
const check=(name,fn)=>{try{fn();checks.push([true,name]);console.log('PASS - '+name)}catch(e){checks.push([false,name]);console.error('FAIL - '+name+' :: '+e.message)}};

const index=read('public/index.html');
const app=read('public/app.js');
const server=read('server.js');
const db=read('database.js');
const storage=read('storage.js');
const vercel=JSON.parse(read('vercel.json'));
const fallback=JSON.parse(read('public/data/catalog-fallback.json'));
const settings=JSON.parse(read('public/data/settings-fallback.json'));
const pkg=JSON.parse(read('package.json'));

check('Home pública existe',()=>assert(exists('public/index.html')));
check('Tailwind está compilado localmente',()=>{assert(index.includes('tailwind-built.css'));assert(exists('public/tailwind-built.css'));assert(!index.includes('cdn.tailwindcss.com'))});
check('Ícones estão locais',()=>{assert(index.includes('vendor/icons.js'));assert(exists('public/vendor/icons.js'));assert(!index.includes('unpkg.com'))});
check('Catálogo fallback válido',()=>{assert(Array.isArray(fallback)&&fallback.length>=10);for(const p of fallback){assert(p.id&&p.sku&&p.name&&p.image);assert(Number(p.price)>=0)}});
check('Imagens fallback locais existem',()=>{for(const p of fallback){if(p.image.startsWith('/images/'))assert(exists('public'+p.image),p.image)}});
check('WhatsApp oficial',()=>assert.strictEqual(String(settings.whatsappNumber).replace(/\D/g,''),'595991950031'));
check('Checkout usa API antes do WhatsApp',()=>{assert(app.includes("fetch('/api/orders'"));assert(app.includes('wa.me'))});
check('Admin usa senha + 2FA autoconfigurável',()=>{assert(index.includes('adminTotpInput'));assert(index.includes('admin2faQrImage'));assert(server.includes('verifyTotp'));assert(server.includes('/api/auth/setup/start'));assert(!server.includes('ADMIN_TOTP_SECRET'))});
check('Admin usa cookie HttpOnly',()=>{assert(server.includes('HttpOnly; SameSite=Strict'));assert(!app.includes('sessionStorage'))});
check('Persistência usa Vercel Blob privado',()=>{assert(db.includes("@vercel/blob"));assert(db.includes("access: 'private'"));assert(storage.includes("@vercel/blob"));assert(storage.includes("access: 'private'"))});
check('Sem PostgreSQL/Supabase/Netlify obrigatório',()=>{assert(!/DATABASE_URL|SUPABASE_SERVICE_ROLE_KEY|@netlify\/blobs|serverless-http|NETLIFY/.test(server+'\n'+db+'\n'+storage+'\n'+JSON.stringify(pkg.dependencies)))});
check('Vercel encaminha APIs ao Express',()=>{assert(Array.isArray(vercel.rewrites));assert(vercel.rewrites.some(r=>r.source==='/api/:path*'&&r.destination==='/api/index'))});
check('Vercel Blob declarado em versão fixa',()=>assert.strictEqual(pkg.dependencies['@vercel/blob'],'2.8.0'));
check('Cadastro mobile permite câmera traseira',()=>{assert(index.includes('capture="environment"'));assert(index.includes('accept="image/*"'))});
check('Galeria de produto permanece implementada',()=>{assert(app.includes('productFormGalleryImages'));assert(app.includes('btn-gallery-main'));assert(app.includes('btn-gallery-remove'))});
check('SEO técnico permanece presente',()=>{assert(index.includes('<meta name="description"'));assert(index.includes('application/ld+json'));assert(server.includes("app.get('/sitemap.xml'"));assert(server.includes("app.get('/robots.txt'"));assert(server.includes("app.get('/llms.txt'"))});
check('OAI-SearchBot permitido e GPTBot separado',()=>{assert(server.includes('OAI-SearchBot'));assert(server.includes('GPTBot'))});
check('QR 2FA é gerado automaticamente',()=>{assert.strictEqual(pkg.dependencies.qrcode,'1.5.4');assert(server.includes('QRCode.toDataURL'));assert(app.includes('showAdmin2faSetup'));assert(index.includes('admin2faManualKey'))});
check('Pacote não contém .env real',()=>assert(!exists('.env')));
check('Arquivos críticos Vercel existem',()=>{for(const f of ['vercel.json','api/index.js','.env.example'])assert(exists(f),f)});
check('Config Netlify removida',()=>{assert(!exists('netlify.toml'));assert(!exists('netlify/functions/api.js'));assert(!exists('public/_redirects'));assert(!exists('public/_headers'))});

const failed=checks.filter(c=>!c[0]);
console.log(`\n${checks.length-failed.length}/${checks.length} verificaciones de release aprobadas.`);
if(failed.length)process.exit(1);
